version: '3.9'

services:
  db:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  trino:
    image: trinodb/trino:latest
    volumes:
      - ./catalog:/etc/trino/catalog
    ports:
      - 8080:8080
    depends_on:
      - db

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9001"

  minio-setup:
    image: minio/mc
    container_name: minio-setup
    environment:
        - MC_HOST_minio=http://minio:minio123@minio:9000
    depends_on:
      - minio
    command: ["mb", "minio/datalake", "minio/datalake-safe", "minio/landingzone"]

  minio-data:
    image: minio/mc
    container_name: minio-data
    environment:
        - MC_HOST_minio=http://minio:minio123@minio:9000
    depends_on:
      - minio-setup
    command: ["cp", "--recursive", "./data/", "minio/landingzone/"]
    volumes:
      - ./data/:/data/:rw

  hive-metastore:
    hostname: hive-metastore
    container_name: hive-metastore
    build:
      context: .
      dockerfile: ./Dockerfile.hive
    ports:
      - 9083:9083
    volumes:
      - ./hive/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_AUX_JARS_PATH: /opt/apache-hive-metastore-3.0.0-bin/auxlib
      METASTORE_DB_HOSTNAME: mariadb
    depends_on:
      - mariadb

  mariadb:
    hostname: mariadb
    container_name: mariadb
    image: mariadb:10.5.8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db