name: 'mark'
version: '1.0.0'
config-version: 2

profile: 'mark'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  mark:
    +database: "{{env_var('PROJECT_NAME')}}_DEV_DATA"
    example:
      +materialized: view
      +schema: marketing