my_project:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: docker.for.mac.localhost
      port: 5432
      user: postgres
      pass: password
      dbname: postgres
      schema: public
  target: dev