
version: 2

models:
  - name: marketing_first_model
    description: '{{ doc("marketing_first_model_docs") }}'
    config:
      grants:
        select: ['fina']
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique

  - name: marketing_second_model
    description: "A starter dbt model"
    columns:
      - name: ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
